Repository aimclub/SAMPO, pull requests merged in 2023-07, with the labels that each got.

#29 Added examples in Jupyter notebooks
  README.rst
  examples/data_preparation.ipynb
  examples/local_optimization.ipynb
  examples/simple_generation.ipynb
  examples/visualization.ipynb
  sampo/generator/environment/contractor_by_wg.py
  sampo/pipeline/base.py
  sampo/pipeline/default.py
  sampo/pipeline/lag_optimization.py
  sampo/scheduler/genetic/schedule_builder.py
  sampo/scheduler/utils/local_optimization.py
  sampo/schemas/contractor.py
  tests/pipeline/basic_pipeline_test.py
Labels: examples

#30 Сompleted documentation
  .readthedocs.yaml
  README.rst
  docs/Makefile
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/source/Features.rst
  docs/source/Install.rst
  docs/source/Usage.rst
  docs/source/_static/AIM-logo.svg
  docs/source/_static/sampo-scheme.jfif
  docs/source/_static/sampo-scheme.jpg
  docs/source/_static/sampo_logo.png
  docs/source/_static/sampo_logo_min.png
  docs/source/_templates/autoapi/index.rst
  docs/source/_templates/autoapi/macros.rst
  docs/source/_templates/autoapi/python/attribute.rst
  docs/source/_templates/autoapi/python/class.rst
  docs/source/_templates/autoapi/python/data.rst
  docs/source/_templates/autoapi/python/exception.rst
  docs/source/_templates/autoapi/python/function.rst
  docs/source/_templates/autoapi/python/method.rst
  docs/source/_templates/autoapi/python/module.rst
  docs/source/_templates/autoapi/python/package.rst
  docs/source/_templates/autoapi/python/property.rst
  docs/source/conf.py
  docs/source/index.rst
  requirements.txt
Labels: documentation

#37 Fixed empty worker requirements handling
  pyproject.toml
  sampo/scheduler/genetic/schedule_builder.py
  tests/scheduler/empty_scheduling_test.py
Labels: bug

#36 The true deadline optimizing
  sampo/scheduler/base.py
  sampo/scheduler/generic.py
  sampo/scheduler/genetic/base.py
  sampo/scheduler/genetic/converter.py
  sampo/scheduler/genetic/operators.py
  sampo/scheduler/genetic/schedule_builder.py
  sampo/scheduler/heft/base.py
  sampo/scheduler/native_wrapper.py
  sampo/scheduler/resources_in_time/average_binary_search.py
  sampo/scheduler/timeline/base.py
  sampo/scheduler/timeline/just_in_time_timeline.py
  sampo/scheduler/timeline/momentum_timeline.py
  sampo/scheduler/topological/base.py
  sampo/scheduler/utils/local_optimization.py
  sampo/scheduler/utils/peaks.py
  sampo/schemas/schedule_spec.py
  tests/scheduler/genetic/fixtures.py
  tests/scheduler/resources_in_time/basic_res_test.py
  tests/scheduler/timeline/just_in_time_timeline_test.py
  tests/scheduler/timeline/momentum_timeline_test.py
Labels: enhancement
