Repository aimclub/SAMPO, pull requests merged in 2024-01, with the labels that each got.

#69 Refactor MomentumTimeline and introduce LFTScheduler
  sampo/scheduler/base.py
  sampo/scheduler/heft/base.py
  sampo/scheduler/lft/__init__.py
  sampo/scheduler/lft/base.py
  sampo/scheduler/lft/prioritization.py
  sampo/scheduler/lft/time_computaion.py
  sampo/scheduler/resource/average_req.py
  sampo/scheduler/timeline/momentum_timeline.py
  sampo/scheduler/topological/base.py
  sampo/schemas/exceptions.py
  sampo/schemas/graph.py
  sampo/schemas/time_estimator.py
  sampo/structurator/base.py
  sampo/utilities/resource_usage.py
  tests/conftest.py
  tests/scheduler/lft/__init__.py
  tests/scheduler/lft/fixtures.py
  tests/scheduler/lft/prioritization_test.py
  tests/scheduler/lft/scheduling_test.py
  tests/structurator/structurator_test.py
Labels: bug, enhancement, refactor

#73 Fix gitlab mirror badge in readme
  README.rst
Labels: bug, documentation

#76 Adapt Genetic Algorithm to multi-objective tasks
  sampo/scheduler/genetic/__init__.py
  sampo/scheduler/genetic/base.py
  sampo/scheduler/genetic/operators.py
  sampo/scheduler/genetic/schedule_builder.py
  sampo/utilities/resource_usage.py
  tests/scheduler/genetic/full_scheduling.py
  tests/scheduler/genetic/multiobjective_scheduling.py
  tests/scheduler/genetic/operators_test.py
  tests/scheduler/resources_in_time/basic_res_test.py
Labels: enhancement
