Repository aimclub/SAMPO, pull requests merged in 2024-02, with the labels that each got.

#78 Fix and refactor LFTScheduler
  sampo/scheduler/generic.py
  sampo/scheduler/lft/base.py
  sampo/scheduler/lft/time_computaion.py
  sampo/scheduler/utils/__init__.py
  tests/conftest.py
  tests/scheduler/genetic/multiobjective_scheduling.py
Labels: bug, refactor

#77 The scalable computations
  sampo/api/__init__.py
  sampo/api/genetic_api.py
  sampo/backend/__init__.py
  sampo/backend/default.py
  sampo/backend/multiproc.py
  sampo/base.py
  sampo/scheduler/genetic/base.py
  sampo/scheduler/genetic/converter.py
  sampo/scheduler/genetic/operators.py
  sampo/scheduler/genetic/schedule_builder.py
  sampo/scheduler/genetic/utils.py
  sampo/scheduler/native_wrapper.py
  sampo/schemas/graph.py
  sampo/schemas/time_estimator.py
  tests/conftest.py
  tests/scheduler/genetic/fixtures.py
  tests/scheduler/genetic/full_scheduling.py
  tests/scheduler/genetic/multiobjective_scheduling.py
  tests/scheduler/genetic/operators_test.py
  tests/scheduler/resources_in_time/basic_res_test.py
Labels: enhancement

#80 Add comments to structurator
  sampo/scheduler/genetic/converter.py
  sampo/structurator/__init__.py
  sampo/structurator/base.py
Labels: documentation

#81 Refactor of scheduling for compatibility with multi-objective optimization
  README.rst
  docs/source/Usage.rst
  examples/field_development/field_development_scheduling.py
  examples/generator_scenarios.py
  examples/local_optimization.ipynb
  examples/scheduling_project.ipynb
  examples/simple_generation.ipynb
  examples/simple_synthetic_graph_scheduling.py
  examples/stochastic_maintenance/aircraft_stochastic_maintenance.py
  examples/visualization.ipynb
  experiments/algorithms_2_multi_agency.py
  experiments/genetic2baseline.py
  experiments/genetic_2_multi_agency.py
  experiments/genetic_init.py
  experiments/neural_network/nn2ma.ipynb
  experiments/neural_network/wg_algo_dataset_generation.py
  experiments/psplib/genetic_PSPLIB.py
  experiments/stochastic_productivity.ipynb
  sampo/backend/multiproc.py
  sampo/pipeline/base.py
  sampo/pipeline/default.py
  sampo/scheduler/base.py
  sampo/scheduler/generic.py
  sampo/scheduler/genetic/base.py
  sampo/scheduler/genetic/operators.py
  sampo/scheduler/genetic/schedule_builder.py
  sampo/scheduler/lft/base.py
  sampo/scheduler/multi_agency/multi_agency.py
  sampo/scheduler/resources_in_time/average_binary_search.py
  sampo/schemas/apply_queue.py
  tests/conftest.py
  tests/pipeline/basic_pipeline_test.py
  tests/scheduler/empty_scheduling_test.py
  tests/scheduler/genetic/converter_test.py
  tests/scheduler/genetic/multiobjective_scheduling.py
  tests/scheduler/lft/scheduling_test.py
  tests/scheduler/material_scheduling_test.py
  tests/scheduler/resources_in_time/basic_res_test.py
  tests/scheduler/timeline/zone_timeline_test.py
Labels: refactor
